services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: whatever
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d whatever"]
      interval: 10s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    container_name: app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://root:root@postgres:5432/whatever
      JWT_SECRET: secret
      TOKEN_TTL: "3600"
      RUST_LOG: info
    volumes:
      - ./migrations:/usr/local/bin/migrations
      - ./uploads:/usr/local/bin/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      app:
        condition: service_started

volumes:
  db-data:
