CREATE TABLE IMAGES (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        car_id      BIGINT NOT NULL
                            REFERENCES cars(id)
                                ON DELETE CASCADE,
                        url         TEXT NOT NULL,
                        created_at  TIMESTAMP NOT NULL DEFAULT NOW()
);