CREATE TYPE user_role AS ENUM ('Admin', 'User');

CREATE TABLE users
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR   NOT NULL UNIQUE,
    email         VARCHAR   NOT NULL UNIQUE,
    password_hash VARCHAR   NOT NULL,
    role          user_role NOT NULL DEFAULT 'User',
    created_at    TIMESTAMP NOT NULL DEFAULT NOW()
);


INSERT INTO users (username, email, password_hash, role)
VALUES ('root',
        'test@test.tt',
            '$2a$12$/jetbqGAN.VGDbaEQ2v0GO7brsZXyFghxqKnuQRDJzHESM/QYENgi', -- bcrypt("root")
        'Admin');