CREATE TYPE user_role AS ENUM ('Admin', 'User');

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR   NOT NULL UNIQUE,
    phone         VARCHAR   NOT NULL UNIQUE,
    email         VARCHAR UNIQUE,
    password_hash VARCHAR   NOT NULL,
    role          user_role NOT NULL DEFAULT 'User',
    created_at    TIMESTAMP NOT NULL DEFAULT NOW()
);


INSERT INTO users (username, phone, email, password_hash, role)
VALUES ('root',
        '+375441234567',
        'test@test.tt',
        '$2a$12$/jetbqGAN.VGDbaEQ2v0GO7brsZXyFghxqKnuQRDJzHESM/QYENgi', -- bcrypt("root")
        'Admin'),
       ('dummy',
        '+375449876543',
        'dummy@dummy.net',
        '$2a$12$N6hfSYaAVPKTKTqglFkrReXaBv/rtJryxdNfzF6lXISoDhVTvypc2', -- bcrypt("password")
        'User');