CREATE TABLE CARS (
                      id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      make VARCHAR NOT NULL,
                      model VARCHAR NOT NULL,
                      year INT NOT NULL,
                      price NUMERIC(10,2) NOT NULL,
                      created_at TIMESTAMP NOT NULL DEFAULT NOW()
);