CREATE TABLE CARS
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make         VARCHAR        NOT NULL,
    model        VARCHAR        NOT NULL,
    year         INT            NOT NULL,
    price        NUMERIC(10, 2) NOT NULL,
    created_at   TIMESTAMP      NOT NULL DEFAULT NOW(),
    description  TEXT,
    mileage      VARCHAR        NOT NULL,
    engine       VARCHAR        NOT NULL,
    transmission VARCHAR        NOT NULL
);

INSERT INTO cars
(make, model, year, price, description, mileage, engine, transmission)
VALUES ('Tesla', 'Model S', 2016, 30000,
        NULL, 70000, 'electric', 'automatic'),
       ('Ford', 'Explorer', 2020, 33000,
        NULL, 80000, '2.3', 'automatic');